
from abaqus import *
from abaqusConstants import *
import random

#size of graphene
diameter = 1
#number of graphene
number = 5

#size of magnesium alloy RVE
length = 20
width = 20
height = 20


#create magnesium alloy RVE
myModel = mdb.models["Model-1"]
mysketch_1 = myModel.ConstrainedSketch(name='mysketch_1', sheetSize=100.0)
mysketch_1.rectangle(point1=(0.0, 0.0), point2=(length, width))
myPart = myModel.Part(name='Part-Base', dimensionality=THREE_D, type=DEFORMABLE_BODY)
myPart.BaseSolidExtrude(sketch=mysketch_1, depth=height)
del mysketch_1

#create graphene
partName = "Part-Graphene-{}".format(diameter)
mysketch_2 = myModel.ConstrainedSketch(name='mysketch_2', sheetSize=5.0)
curve = mysketch_2.CircleByCenterPerimeter(center=(0.0, 0.0), point1=(diameter/2.0, 0.0))
myPart2 = myModel.Part(name=partName, dimensionality=THREE_D, type=DEFORMABLE_BODY)
myPart2.BaseShell(sketch=mysketch_2)
del mysketch_2

#interaction judge
def interCheck(point,center,radius1,radius2):
    sign = True
    for p in center:
        if sqrt((point[0]-p[0])**2+(point[1]-p[1])**2+(point[2]-p[2])**2) <= (radius1+radius2):
            sign = False
            break
    return sign

# caculate diameter
count = 0
center1 = []
radius = diameter/2.0

while True:
    disX = random.uniform(radius, length-radius)
    disY = random.uniform(radius, width-radius)
    disZ = random.uniform(radius, height-radius)
   
    if len(center1)==0:
        center1.append([disX,disY,disZ])
    else:
        if interCheck([disX,disY,disZ],center1,radius,radius):
            center1.append([disX,disY,disZ])
    count += 1
    if len(center1)==number:
        break
    elif count >= float(length*width*height)/diameter**3:
        break
    else:
        pass

#translate graphene
myAssembly = myModel.rootAssembly
for index in range(len(center1)):
    myAssembly.Instance(name='Part-Graphene-{}-{}'.format(diameter,index), part=myModel.parts["Part-Graphene-{}".format(diameter)], dependent=ON)
    myAssembly.translate(instanceList=('Part-Graphene-{}-{}'.format(diameter,index),), vector=tuple(center1[index]))
